services:
  nest-app:
    container_name: nest-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      mysql-container:
        condition: service_healthy
      redis-container:
        condition: service_healthy
    env_file:
      - ./dist/.env
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@mysql-container:3306/${MYSQL_DATABASE}
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      LOG_LEVEL: info
    ports:
      - '3000:3000'
    networks: 
      - common-network
  mysql-container:
    container_name: mysql-container
    image: mysql
    volumes:
      - /Users/Jiazhigang/Desktop/my-event/vue3-app-container/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-padminroot", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks: 
      - common-network
  redis-container:
    container_name: redis-container
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /Users/Jiazhigang/Desktop/my-event/vue3-app-container/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: 
      - common-network
networks:
  common-network:
    driver: bridge
